baseURL = "https://example.com/"
title = "The Ordinary Singaporean Dad"
languageCode = "en-us"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowShareButtons = false
  comments = false

  [params.homeInfoParams]
    Title = "The Ordinary Singaporean Dad"
    Content = "A Singaporean dad writing about whatever."

  [[params.socialIcons]]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 4
